 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjp6yuSVM_Sgp34K8K7JRjAVZWyw-HHCA',
    appId: '1:608404626932:web:1c76fe64e57607e3a3eda1',
    messagingSenderId: '608404626932',
    projectId: 'chat-app-4fc6b',
    authDomain: 'chat-app-4fc6b.firebaseapp.com',
    storageBucket: 'chat-app-4fc6b.appspot.com',
    measurementId: 'G-NFND5S9D2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSsmYdzGO9ZeZjaejEVrp3wX3ynucRrFk',
    appId: '1:608404626932:android:ae703d06e3e6ad5ba3eda1',
    messagingSenderId: '608404626932',
    projectId: 'chat-app-4fc6b',
    storageBucket: 'chat-app-4fc6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpqK2KWM9i81PV2VnDgRTOfTwH-cudcSU',
    appId: '1:608404626932:ios:4c6a0b47bc590dd2a3eda1',
    messagingSenderId: '608404626932',
    projectId: 'chat-app-4fc6b',
    storageBucket: 'chat-app-4fc6b.appspot.com',
    iosBundleId: 'com.chatapp.usf.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpqK2KWM9i81PV2VnDgRTOfTwH-cudcSU',
    appId: '1:608404626932:ios:079601d560618073a3eda1',
    messagingSenderId: '608404626932',
    projectId: 'chat-app-4fc6b',
    storageBucket: 'chat-app-4fc6b.appspot.com',
    iosBundleId: 'com.chatapp.usf.scholarChat.RunnerTests',
  );
}
